### ISSUE TITLE
Adicionar o output do Terraform plan no PR

### ISSUE THREAD

**Issue by marcelomansur** [mentoriaiac/iac-groundwork#3]
**Objetivo**: Precisamos que o plano de execução do Terraform seja adicionado como comentário do PR.

Pode ser usado como referência: https://github.com/nerdtux/iac-modulo-rede-gcp/blob/main/.github/workflows/ci_plan.yml#L68

**DoD**:

- [ ] PR aberto com o output do `terraform plan` nos comentários.

**Comment by gomex** [comment]
Perdeu sentido pq não rodaremos plan no PR.
