### ISSUE TITLE
Validar se PR de fork consegue usar o secret

### ISSUE THREAD

**Issue by marcelomansur** [mentoriaiac/iac-groundwork#4]
**Objetivo**: Precisamos validar se um PR a partir de um fork consegue consumir as secrets no pipeline deste projeto.

**DoD**:

- [ ] PR aberto que consiga executar um `terraform plan` autenticado no GCP da Mentoria.

**Comment by snifbr** [comment]
A princípio quando fomos subir o PR do meu fork que resolve o issue #3 não foram utilizadas as variáveis do secrets e não foi possível validar o terraform plan via PR.

Segue imagem comprovando o não uso dos secrets:
![image](https://user-images.githubusercontent.com/11183983/136478181-e0ab0f75-ed7f-4416-a89a-594b8d0d5bb4.png)

**Comment by gomex** [comment]
Eu não acho que devemos permitir acessa a nosso dados no PR. Vou fechar essa issue por agora, mas se acharmos uma forma segura, podemos reabrir, ok?
